"""Public imports resolved on demand to keep the exchange core isolated."""

from __future__ import annotations

from importlib import import_module
from typing import TYPE_CHECKING
from warnings import warn

from cxp._version import __version__, version_info

if TYPE_CHECKING:
    from cxp.capabilities import (
        Capability,
        CapabilityMatrix,
        CapabilityMetadata,
    )
    from cxp.catalogs import (
        ASGI_APPLICATION_CATALOG,
        ASGI_APPLICATION_EARLY_HINTS,
        ASGI_APPLICATION_EARLY_HINTS_PROFILE,
        ASGI_APPLICATION_EARLY_HINTS_PROFILE_NAME,
        ASGI_APPLICATION_EXTENDED_HTTP_PROFILE,
        ASGI_APPLICATION_EXTENDED_HTTP_PROFILE_NAME,
        ASGI_APPLICATION_HTTP,
        ASGI_APPLICATION_HTTP_CORE_PROFILE,
        ASGI_APPLICATION_HTTP_CORE_PROFILE_NAME,
        ASGI_APPLICATION_HTTP_CORE_TIER,
        ASGI_APPLICATION_HTTP_DISCONNECT_RECEIVE,
        ASGI_APPLICATION_HTTP_EARLY_HINT,
        ASGI_APPLICATION_HTTP_PATH_SEND,
        ASGI_APPLICATION_HTTP_PUSH,
        ASGI_APPLICATION_HTTP_REQUEST_RECEIVE,
        ASGI_APPLICATION_HTTP_RESPONSE_BODY,
        ASGI_APPLICATION_HTTP_RESPONSE_START,
        ASGI_APPLICATION_HTTP_SCOPE_INSPECT,
        ASGI_APPLICATION_HTTP_SERVER_PUSH,
        ASGI_APPLICATION_HTTP_TRAILERS,
        ASGI_APPLICATION_HTTP_ZERO_COPY_SEND,
        ASGI_APPLICATION_INTERFACE,
        ASGI_APPLICATION_LIFESPAN,
        ASGI_APPLICATION_LIFESPAN_PROFILE,
        ASGI_APPLICATION_LIFESPAN_PROFILE_NAME,
        ASGI_APPLICATION_LIFESPAN_SCOPE_INSPECT,
        ASGI_APPLICATION_LIFESPAN_SHUTDOWN_COMPLETE,
        ASGI_APPLICATION_LIFESPAN_SHUTDOWN_FAILED,
        ASGI_APPLICATION_LIFESPAN_SHUTDOWN_RECEIVE,
        ASGI_APPLICATION_LIFESPAN_STARTUP_COMPLETE,
        ASGI_APPLICATION_LIFESPAN_STARTUP_FAILED,
        ASGI_APPLICATION_LIFESPAN_STARTUP_RECEIVE,
        ASGI_APPLICATION_PATH_SEND,
        ASGI_APPLICATION_REALTIME_PROFILE,
        ASGI_APPLICATION_REALTIME_PROFILE_NAME,
        ASGI_APPLICATION_REALTIME_TIER,
        ASGI_APPLICATION_TLS,
        ASGI_APPLICATION_TLS_AWARE_PROFILE,
        ASGI_APPLICATION_TLS_AWARE_PROFILE_NAME,
        ASGI_APPLICATION_TLS_SCOPE_INSPECT,
        ASGI_APPLICATION_TRAILERS,
        ASGI_APPLICATION_WEB_CORE_PROFILE,
        ASGI_APPLICATION_WEB_CORE_PROFILE_NAME,
        ASGI_APPLICATION_WEB_CORE_TIER,
        ASGI_APPLICATION_WEBSOCKET,
        ASGI_APPLICATION_WEBSOCKET_ACCEPT,
        ASGI_APPLICATION_WEBSOCKET_CLOSE,
        ASGI_APPLICATION_WEBSOCKET_CONNECT_RECEIVE,
        ASGI_APPLICATION_WEBSOCKET_DENIAL_PROFILE,
        ASGI_APPLICATION_WEBSOCKET_DENIAL_PROFILE_NAME,
        ASGI_APPLICATION_WEBSOCKET_DENIAL_RESPONSE,
        ASGI_APPLICATION_WEBSOCKET_DISCONNECT_RECEIVE,
        ASGI_APPLICATION_WEBSOCKET_HTTP_RESPONSE_BODY,
        ASGI_APPLICATION_WEBSOCKET_HTTP_RESPONSE_START,
        ASGI_APPLICATION_WEBSOCKET_RECEIVE,
        ASGI_APPLICATION_WEBSOCKET_SCOPE_INSPECT,
        ASGI_APPLICATION_WEBSOCKET_SEND,
        ASGI_APPLICATION_ZERO_COPY_SEND,
        BROWSER_AUTOMATION_CATALOG,
        BROWSER_AUTOMATION_INTERFACE,
        COSECHA_ENGINE_CATALOG,
        COSECHA_ENGINE_COLLECT,
        COSECHA_ENGINE_DEFINITION_KNOWLEDGE,
        COSECHA_ENGINE_DEFINITION_RESOLVE,
        COSECHA_ENGINE_DEPENDENCIES_DESCRIBE,
        COSECHA_ENGINE_DEPENDENCY_KNOWLEDGE,
        COSECHA_ENGINE_DRAFT_VALIDATE,
        COSECHA_ENGINE_DRAFT_VALIDATION,
        COSECHA_ENGINE_INTERFACE,
        COSECHA_ENGINE_KNOWLEDGE_QUERY_DEFINITIONS,
        COSECHA_ENGINE_KNOWLEDGE_QUERY_REGISTRY_ITEMS,
        COSECHA_ENGINE_KNOWLEDGE_QUERY_TESTS,
        COSECHA_ENGINE_LIBRARY_DEFINITION_KNOWLEDGE,
        COSECHA_ENGINE_LIFECYCLE,
        COSECHA_ENGINE_ON_DEMAND_DEFINITION_MATERIALIZATION,
        COSECHA_ENGINE_PLAN_ANALYZE,
        COSECHA_ENGINE_PLAN_EXPLAIN,
        COSECHA_ENGINE_PLAN_EXPLANATION,
        COSECHA_ENGINE_PLAN_SIMULATE,
        COSECHA_ENGINE_PROJECT_DEFINITION_KNOWLEDGE,
        COSECHA_ENGINE_PROJECT_REGISTRY_KNOWLEDGE,
        COSECHA_ENGINE_SELECTION_LABELS,
        COSECHA_ENGINE_SESSION_FINISH,
        COSECHA_ENGINE_SESSION_START,
        COSECHA_ENGINE_STATIC_DEFINITION_DISCOVERY,
        COSECHA_ENGINE_TEST_EXECUTE,
        COSECHA_ENGINE_TEST_FINISH,
        COSECHA_ENGINE_TEST_LIFECYCLE,
        COSECHA_ENGINE_TEST_PHASE,
        COSECHA_ENGINE_TEST_START,
        COSECHA_INSTRUMENTATION_ACTIVATE,
        COSECHA_INSTRUMENTATION_CATALOG,
        COSECHA_INSTRUMENTATION_COMPOSABLE_PROFILE,
        COSECHA_INSTRUMENTATION_COMPOSABLE_PROFILE_NAME,
        COSECHA_INSTRUMENTATION_COMPOSABLE_TIER,
        COSECHA_INSTRUMENTATION_INTERFACE,
        COSECHA_INSTRUMENTATION_SLOT_PROCESS_ARGV,
        COSECHA_INSTRUMENTATION_SLOT_PROCESS_ENV,
        COSECHA_INSTRUMENTATION_SLOT_PROCESS_SITECUSTOMIZE,
        COSECHA_INSTRUMENTATION_SLOT_PY_MONITORING,
        COSECHA_INSTRUMENTATION_SLOT_PY_SETPROFILE,
        COSECHA_INSTRUMENTATION_SLOT_PY_SETTRACE,
        COSECHA_INSTRUMENTATION_STRATEGY_IN_PROCESS,
        COSECHA_INSTRUMENTATION_STRATEGY_PROCESS_WRAPPER,
        COSECHA_INSTRUMENTATION_STRATEGY_SITECUSTOMIZE,
        COSECHA_INSTRUMENTATION_STRUCTURED_SUMMARY,
        COSECHA_PLUGIN_AFTER_SESSION_CLOSED,
        COSECHA_PLUGIN_CAPABILITY_REQUIREMENTS,
        COSECHA_PLUGIN_CATALOG,
        COSECHA_PLUGIN_COVERAGE_SUMMARY,
        COSECHA_PLUGIN_FINISH,
        COSECHA_PLUGIN_INITIALIZE,
        COSECHA_PLUGIN_INTERFACE,
        COSECHA_PLUGIN_LIFECYCLE,
        COSECHA_PLUGIN_START,
        COSECHA_PLUGIN_SURFACE_PUBLICATION,
        COSECHA_PLUGIN_TELEMETRY_EXPORT,
        COSECHA_PLUGIN_TELEMETRY_SIDECAR_PROFILE,
        COSECHA_PLUGIN_TELEMETRY_SIDECAR_PROFILE_NAME,
        COSECHA_PLUGIN_TELEMETRY_SIDECAR_TIER,
        COSECHA_PLUGIN_TIMING_SIDECAR_PROFILE,
        COSECHA_PLUGIN_TIMING_SIDECAR_PROFILE_NAME,
        COSECHA_PLUGIN_TIMING_SIDECAR_TIER,
        COSECHA_PLUGIN_TIMING_SUMMARY,
        COSECHA_REPORTER_ADD_TEST,
        COSECHA_REPORTER_ADD_TEST_RESULT,
        COSECHA_REPORTER_ARTIFACT_OUTPUT,
        COSECHA_REPORTER_CATALOG,
        COSECHA_REPORTER_HUMAN_OUTPUT,
        COSECHA_REPORTER_INTERFACE,
        COSECHA_REPORTER_PRINT_REPORT,
        COSECHA_REPORTER_REPORT_LIFECYCLE,
        COSECHA_REPORTER_RESULT_PROJECTION,
        COSECHA_REPORTER_START,
        COSECHA_REPORTER_STRUCTURED_OUTPUT,
        COSECHA_RUNTIME_CATALOG,
        COSECHA_RUNTIME_INTERFACE,
        COSECHA_RUNTIME_LIVE_EXECUTION_OBSERVABILITY,
        DEFAULT_CATALOG_REGISTRY,
        EXECUTION_ENGINE_CATALOG,
        EXECUTION_ENGINE_EXECUTION_STATUS,
        EXECUTION_ENGINE_EXECUTION_STREAM,
        EXECUTION_ENGINE_FAMILY_CATALOG,
        EXECUTION_ENGINE_FAMILY_INTERFACE,
        EXECUTION_ENGINE_INPUT_VALIDATION,
        EXECUTION_ENGINE_INTERFACE,
        EXECUTION_ENGINE_PLANNING,
        EXECUTION_ENGINE_RUN,
        HTTP_APPLICATION_CATALOG,
        HTTP_APPLICATION_FRAMEWORK_AUTH_PROCESSING,
        HTTP_APPLICATION_FRAMEWORK_CATALOG,
        HTTP_APPLICATION_FRAMEWORK_CORE_TIER,
        HTTP_APPLICATION_FRAMEWORK_DEPENDENCY_INJECTION,
        HTTP_APPLICATION_FRAMEWORK_INTERFACE,
        HTTP_APPLICATION_FRAMEWORK_ROUTING,
        HTTP_APPLICATION_FRAMEWORK_SCHEMA_VALIDATION,
        HTTP_APPLICATION_INTERFACE,
        HTTP_TRANSPORT_AUTH_PROPAGATION,
        HTTP_TRANSPORT_CATALOG,
        HTTP_TRANSPORT_COOKIES,
        HTTP_TRANSPORT_CORE_TIER,
        HTTP_TRANSPORT_HEADERS,
        HTTP_TRANSPORT_INTERFACE,
        HTTP_TRANSPORT_MIDDLEWARE_OBSERVABLE,
        HTTP_TRANSPORT_NETWORK_TRANSPORT,
        HTTP_TRANSPORT_STREAMING,
        MONGODB_AGGREGATE,
        MONGODB_AGGREGATE_RICH_PROFILE,
        MONGODB_AGGREGATE_RICH_PROFILE_NAME,
        MONGODB_AGGREGATION,
        MONGODB_BULK_WRITE,
        MONGODB_CATALOG,
        MONGODB_CHANGE_STREAMS,
        MONGODB_COLLATION,
        MONGODB_CORE_PROFILE,
        MONGODB_CORE_PROFILE_NAME,
        MONGODB_CORE_TIER,
        MONGODB_COUNT_DOCUMENTS,
        MONGODB_DELETE_MANY,
        MONGODB_DELETE_ONE,
        MONGODB_DISTINCT,
        MONGODB_ESTIMATED_DOCUMENT_COUNT,
        MONGODB_FIND,
        MONGODB_FIND_ONE,
        MONGODB_FULL_CAPABILITIES,
        MONGODB_INSERT_MANY,
        MONGODB_INSERT_ONE,
        MONGODB_INTERFACE,
        MONGODB_MINIMAL_CAPABILITIES,
        MONGODB_PERSISTENCE,
        MONGODB_PLATFORM_PROFILE,
        MONGODB_PLATFORM_PROFILE_NAME,
        MONGODB_PLATFORM_TIER,
        MONGODB_READ,
        MONGODB_REPLACE_ONE,
        MONGODB_SEARCH,
        MONGODB_SEARCH_PROFILE,
        MONGODB_SEARCH_PROFILE_NAME,
        MONGODB_SEARCH_TIER,
        MONGODB_START_SESSION,
        MONGODB_TEXT_SEARCH_PROFILE,
        MONGODB_TEXT_SEARCH_PROFILE_NAME,
        MONGODB_TOPOLOGY_DISCOVERY,
        MONGODB_TRANSACTIONS,
        MONGODB_UPDATE_MANY,
        MONGODB_UPDATE_ONE,
        MONGODB_VECTOR_SEARCH,
        MONGODB_WATCH,
        MONGODB_WITH_TRANSACTION,
        MONGODB_WRITE,
        PLAN_RUN_EXECUTION_ADVANCED_PROFILE,
        PLAN_RUN_EXECUTION_ADVANCED_PROFILE_NAME,
        PLAN_RUN_EXECUTION_CATALOG,
        PLAN_RUN_EXECUTION_CORE_PROFILE,
        PLAN_RUN_EXECUTION_CORE_PROFILE_NAME,
        PLAN_RUN_EXECUTION_EXECUTION_STATUS,
        PLAN_RUN_EXECUTION_EXECUTION_STREAM,
        PLAN_RUN_EXECUTION_INPUT_VALIDATION,
        PLAN_RUN_EXECUTION_INTERFACE,
        PLAN_RUN_EXECUTION_PLANNED_PROFILE,
        PLAN_RUN_EXECUTION_PLANNED_PROFILE_NAME,
        PLAN_RUN_EXECUTION_PLANNING,
        PLAN_RUN_EXECUTION_RUN,
        PLAYWRIGHT_BROWSER_CATALOG,
        PLAYWRIGHT_BROWSER_CLOSE,
        PLAYWRIGHT_BROWSER_CONTEXT_CLOSE,
        PLAYWRIGHT_BROWSER_CONTEXT_CREATE,
        PLAYWRIGHT_BROWSER_CONTEXT_MANAGEMENT,
        PLAYWRIGHT_BROWSER_CORE_PROFILE,
        PLAYWRIGHT_BROWSER_CORE_PROFILE_NAME,
        PLAYWRIGHT_BROWSER_CORE_TIER,
        PLAYWRIGHT_BROWSER_DIALOG_ACCEPT,
        PLAYWRIGHT_BROWSER_DIALOG_DISMISS,
        PLAYWRIGHT_BROWSER_DIALOG_HANDLING,
        PLAYWRIGHT_BROWSER_DOM_INTERACTION,
        PLAYWRIGHT_BROWSER_ELEMENT_CLICK,
        PLAYWRIGHT_BROWSER_ELEMENT_EVALUATE,
        PLAYWRIGHT_BROWSER_ELEMENT_FILL,
        PLAYWRIGHT_BROWSER_ELEMENT_PRESS,
        PLAYWRIGHT_BROWSER_ELEMENT_SCREENSHOT,
        PLAYWRIGHT_BROWSER_ELEMENT_SELECT_OPTION,
        PLAYWRIGHT_BROWSER_INTERFACE,
        PLAYWRIGHT_BROWSER_LAUNCH,
        PLAYWRIGHT_BROWSER_LIFECYCLE,
        PLAYWRIGHT_BROWSER_LOCATOR_FILTER,
        PLAYWRIGHT_BROWSER_LOCATOR_QUERY,
        PLAYWRIGHT_BROWSER_LOCATOR_RESOLUTION,
        PLAYWRIGHT_BROWSER_NETWORK_OBSERVATION,
        PLAYWRIGHT_BROWSER_NETWORK_REQUEST_OBSERVE,
        PLAYWRIGHT_BROWSER_NETWORK_RESPONSE_OBSERVE,
        PLAYWRIGHT_BROWSER_OBSERVABLE_PROFILE,
        PLAYWRIGHT_BROWSER_OBSERVABLE_PROFILE_NAME,
        PLAYWRIGHT_BROWSER_OBSERVABLE_TIER,
        PLAYWRIGHT_BROWSER_PAGE_EVALUATE,
        PLAYWRIGHT_BROWSER_PAGE_GO_BACK,
        PLAYWRIGHT_BROWSER_PAGE_GOTO,
        PLAYWRIGHT_BROWSER_PAGE_NAVIGATION,
        PLAYWRIGHT_BROWSER_PAGE_RELOAD,
        PLAYWRIGHT_BROWSER_PAGE_SCREENSHOT,
        PLAYWRIGHT_BROWSER_SCREENSHOT_CAPTURE,
        PLAYWRIGHT_BROWSER_SCRIPT_EVALUATION,
        PLAYWRIGHT_BROWSER_WAIT_CONDITIONS,
        PLAYWRIGHT_BROWSER_WAIT_FOR_RESPONSE,
        PLAYWRIGHT_BROWSER_WAIT_FOR_SELECTOR,
        PLAYWRIGHT_BROWSER_WAIT_FOR_URL,
        WSGI_APPLICATION_CATALOG,
        WSGI_APPLICATION_CORE_PROFILE,
        WSGI_APPLICATION_CORE_PROFILE_NAME,
        WSGI_APPLICATION_CORE_TIER,
        WSGI_APPLICATION_FILE_WRAPPER,
        WSGI_APPLICATION_FILE_WRAPPER_PROFILE,
        WSGI_APPLICATION_FILE_WRAPPER_PROFILE_NAME,
        WSGI_APPLICATION_HTTP,
        WSGI_APPLICATION_INTERFACE,
        WSGI_APPLICATION_OPTIMIZED_TIER,
        WSGI_APPLICATION_REQUEST_BODY_READ,
        WSGI_APPLICATION_REQUEST_ENVIRON_INSPECT,
        WSGI_APPLICATION_RESPONSE_BODY_FILE_WRAPPER,
        WSGI_APPLICATION_RESPONSE_BODY_ITERABLE,
        WSGI_APPLICATION_RESPONSE_BODY_WRITE,
        WSGI_APPLICATION_RESPONSE_START,
        CapabilityCatalog,
        CapabilityMatrixValidationResult,
        CapabilityMetadataSchema,
        CapabilityProfile,
        CapabilityProfileDefinitionValidationResult,
        CapabilityProfileValidationResult,
        CapabilityRequirement,
        CapabilityTelemetry,
        CatalogCapability,
        CatalogOperation,
        CatalogRegistry,
        ConformanceTier,
        DescriptorValidationResult,
        MongoAggregationMetadata,
        MongoCollationMetadata,
        MongoPersistenceMetadata,
        MongoSearchMetadata,
        MongoTopologyDiscoveryMetadata,
        MongoVectorSearchMetadata,
        TelemetryEventSpec,
        TelemetryFieldRequirement,
        TelemetryMetricSpec,
        TelemetrySpanSpec,
        TelemetryValidationResult,
        UnknownCapabilityOperations,
        catalog_satisfies_interface,
        get_catalog,
        register_catalog,
    )
    from cxp.compliance import CatalogComplianceReport, NegotiatedCatalogDecision
    from cxp.contracts import (
        AsyncCapabilityProvider,
        AsyncCapabilitySnapshotProvider,
        AsyncTelemetryProvider,
        AsyncTelemetryStreamProvider,
        CapabilityProvider,
        CapabilitySnapshotProvider,
        ProtocolVersionProvider,
        TelemetryProvider,
        TelemetryStreamProvider,
    )
    from cxp.descriptors import (
        CapabilityAttribute,
        CapabilityAttributeValue,
        CapabilityDescriptor,
        CapabilityOperationBinding,
        CapabilityStability,
        CapabilitySupportLevel,
        ComponentCapabilitySnapshot,
        ComponentDependencyRule,
    )
    from cxp.handshake import (
        CURRENT_PROTOCOL_VERSION,
        SUPPORTED_PROTOCOL_VERSIONS,
        HandshakeRequest,
        HandshakeResponse,
        is_protocol_version_supported,
        negotiate_capabilities,
        negotiate_protocol_version,
    )
    from cxp.integration import (
        collect_provider_capability_snapshot,
        collect_provider_capability_snapshot_async,
        collect_provider_telemetry,
        collect_provider_telemetry_async,
        evaluate_capability_matrix_against_catalog,
        evaluate_handshake_response_against_catalog,
        negotiate_with_async_provider,
        negotiate_with_async_provider_catalog,
        negotiate_with_async_provider_catalog_report,
        negotiate_with_provider,
        negotiate_with_provider_catalog,
        negotiate_with_provider_catalog_report,
        stream_provider_telemetry,
        stream_provider_telemetry_async,
    )
    from cxp.telemetry import (
        ComponentStatus,
        TelemetryBuffer,
        TelemetryBufferOverflow,
        TelemetryContext,
        TelemetryEvent,
        TelemetryMetric,
        TelemetryOverflowPolicy,
        TelemetrySnapshot,
        TelemetrySpan,
    )
    from cxp.types import ComponentIdentity, Interface, Provider, Version
    from cxp.validation import (
        ContractValidationError,
        ValidationIssue,
        ValidationResult,
    )

_EXPORT_MODULES = {
    "ASGI_APPLICATION_CATALOG": "cxp.catalogs",
    "ASGI_APPLICATION_EARLY_HINTS": "cxp.catalogs",
    "ASGI_APPLICATION_EARLY_HINTS_PROFILE": "cxp.catalogs",
    "ASGI_APPLICATION_EARLY_HINTS_PROFILE_NAME": "cxp.catalogs",
    "ASGI_APPLICATION_EXTENDED_HTTP_PROFILE": "cxp.catalogs",
    "ASGI_APPLICATION_EXTENDED_HTTP_PROFILE_NAME": "cxp.catalogs",
    "ASGI_APPLICATION_HTTP": "cxp.catalogs",
    "ASGI_APPLICATION_HTTP_CORE_PROFILE": "cxp.catalogs",
    "ASGI_APPLICATION_HTTP_CORE_PROFILE_NAME": "cxp.catalogs",
    "ASGI_APPLICATION_HTTP_CORE_TIER": "cxp.catalogs",
    "ASGI_APPLICATION_HTTP_DISCONNECT_RECEIVE": "cxp.catalogs",
    "ASGI_APPLICATION_HTTP_EARLY_HINT": "cxp.catalogs",
    "ASGI_APPLICATION_HTTP_PATH_SEND": "cxp.catalogs",
    "ASGI_APPLICATION_HTTP_PUSH": "cxp.catalogs",
    "ASGI_APPLICATION_HTTP_REQUEST_RECEIVE": "cxp.catalogs",
    "ASGI_APPLICATION_HTTP_RESPONSE_BODY": "cxp.catalogs",
    "ASGI_APPLICATION_HTTP_RESPONSE_START": "cxp.catalogs",
    "ASGI_APPLICATION_HTTP_SCOPE_INSPECT": "cxp.catalogs",
    "ASGI_APPLICATION_HTTP_SERVER_PUSH": "cxp.catalogs",
    "ASGI_APPLICATION_HTTP_TRAILERS": "cxp.catalogs",
    "ASGI_APPLICATION_HTTP_ZERO_COPY_SEND": "cxp.catalogs",
    "ASGI_APPLICATION_INTERFACE": "cxp.catalogs",
    "ASGI_APPLICATION_LIFESPAN": "cxp.catalogs",
    "ASGI_APPLICATION_LIFESPAN_PROFILE": "cxp.catalogs",
    "ASGI_APPLICATION_LIFESPAN_PROFILE_NAME": "cxp.catalogs",
    "ASGI_APPLICATION_LIFESPAN_SCOPE_INSPECT": "cxp.catalogs",
    "ASGI_APPLICATION_LIFESPAN_SHUTDOWN_COMPLETE": "cxp.catalogs",
    "ASGI_APPLICATION_LIFESPAN_SHUTDOWN_FAILED": "cxp.catalogs",
    "ASGI_APPLICATION_LIFESPAN_SHUTDOWN_RECEIVE": "cxp.catalogs",
    "ASGI_APPLICATION_LIFESPAN_STARTUP_COMPLETE": "cxp.catalogs",
    "ASGI_APPLICATION_LIFESPAN_STARTUP_FAILED": "cxp.catalogs",
    "ASGI_APPLICATION_LIFESPAN_STARTUP_RECEIVE": "cxp.catalogs",
    "ASGI_APPLICATION_PATH_SEND": "cxp.catalogs",
    "ASGI_APPLICATION_REALTIME_PROFILE": "cxp.catalogs",
    "ASGI_APPLICATION_REALTIME_PROFILE_NAME": "cxp.catalogs",
    "ASGI_APPLICATION_REALTIME_TIER": "cxp.catalogs",
    "ASGI_APPLICATION_TLS": "cxp.catalogs",
    "ASGI_APPLICATION_TLS_AWARE_PROFILE": "cxp.catalogs",
    "ASGI_APPLICATION_TLS_AWARE_PROFILE_NAME": "cxp.catalogs",
    "ASGI_APPLICATION_TLS_SCOPE_INSPECT": "cxp.catalogs",
    "ASGI_APPLICATION_TRAILERS": "cxp.catalogs",
    "ASGI_APPLICATION_WEBSOCKET": "cxp.catalogs",
    "ASGI_APPLICATION_WEBSOCKET_ACCEPT": "cxp.catalogs",
    "ASGI_APPLICATION_WEBSOCKET_CLOSE": "cxp.catalogs",
    "ASGI_APPLICATION_WEBSOCKET_CONNECT_RECEIVE": "cxp.catalogs",
    "ASGI_APPLICATION_WEBSOCKET_DENIAL_PROFILE": "cxp.catalogs",
    "ASGI_APPLICATION_WEBSOCKET_DENIAL_PROFILE_NAME": "cxp.catalogs",
    "ASGI_APPLICATION_WEBSOCKET_DENIAL_RESPONSE": "cxp.catalogs",
    "ASGI_APPLICATION_WEBSOCKET_DISCONNECT_RECEIVE": "cxp.catalogs",
    "ASGI_APPLICATION_WEBSOCKET_HTTP_RESPONSE_BODY": "cxp.catalogs",
    "ASGI_APPLICATION_WEBSOCKET_HTTP_RESPONSE_START": "cxp.catalogs",
    "ASGI_APPLICATION_WEBSOCKET_RECEIVE": "cxp.catalogs",
    "ASGI_APPLICATION_WEBSOCKET_SCOPE_INSPECT": "cxp.catalogs",
    "ASGI_APPLICATION_WEBSOCKET_SEND": "cxp.catalogs",
    "ASGI_APPLICATION_WEB_CORE_PROFILE": "cxp.catalogs",
    "ASGI_APPLICATION_WEB_CORE_PROFILE_NAME": "cxp.catalogs",
    "ASGI_APPLICATION_WEB_CORE_TIER": "cxp.catalogs",
    "ASGI_APPLICATION_ZERO_COPY_SEND": "cxp.catalogs",
    "AsyncCapabilityProvider": "cxp.contracts",
    "AsyncCapabilitySnapshotProvider": "cxp.contracts",
    "AsyncTelemetryProvider": "cxp.contracts",
    "AsyncTelemetryStreamProvider": "cxp.contracts",
    "BROWSER_AUTOMATION_CATALOG": "cxp.catalogs",
    "BROWSER_AUTOMATION_INTERFACE": "cxp.catalogs",
    "COSECHA_ENGINE_CATALOG": "cxp.catalogs",
    "COSECHA_ENGINE_COLLECT": "cxp.catalogs",
    "COSECHA_ENGINE_DEFINITION_KNOWLEDGE": "cxp.catalogs",
    "COSECHA_ENGINE_DEFINITION_RESOLVE": "cxp.catalogs",
    "COSECHA_ENGINE_DEPENDENCIES_DESCRIBE": "cxp.catalogs",
    "COSECHA_ENGINE_DEPENDENCY_KNOWLEDGE": "cxp.catalogs",
    "COSECHA_ENGINE_DRAFT_VALIDATE": "cxp.catalogs",
    "COSECHA_ENGINE_DRAFT_VALIDATION": "cxp.catalogs",
    "COSECHA_ENGINE_INTERFACE": "cxp.catalogs",
    "COSECHA_ENGINE_KNOWLEDGE_QUERY_DEFINITIONS": "cxp.catalogs",
    "COSECHA_ENGINE_KNOWLEDGE_QUERY_REGISTRY_ITEMS": "cxp.catalogs",
    "COSECHA_ENGINE_KNOWLEDGE_QUERY_TESTS": "cxp.catalogs",
    "COSECHA_ENGINE_LIBRARY_DEFINITION_KNOWLEDGE": "cxp.catalogs",
    "COSECHA_ENGINE_LIFECYCLE": "cxp.catalogs",
    "COSECHA_ENGINE_ON_DEMAND_DEFINITION_MATERIALIZATION": "cxp.catalogs",
    "COSECHA_ENGINE_PLAN_ANALYZE": "cxp.catalogs",
    "COSECHA_ENGINE_PLAN_EXPLAIN": "cxp.catalogs",
    "COSECHA_ENGINE_PLAN_EXPLANATION": "cxp.catalogs",
    "COSECHA_ENGINE_PLAN_SIMULATE": "cxp.catalogs",
    "COSECHA_ENGINE_PROJECT_DEFINITION_KNOWLEDGE": "cxp.catalogs",
    "COSECHA_ENGINE_PROJECT_REGISTRY_KNOWLEDGE": "cxp.catalogs",
    "COSECHA_ENGINE_SELECTION_LABELS": "cxp.catalogs",
    "COSECHA_ENGINE_SESSION_FINISH": "cxp.catalogs",
    "COSECHA_ENGINE_SESSION_START": "cxp.catalogs",
    "COSECHA_ENGINE_STATIC_DEFINITION_DISCOVERY": "cxp.catalogs",
    "COSECHA_ENGINE_TEST_EXECUTE": "cxp.catalogs",
    "COSECHA_ENGINE_TEST_FINISH": "cxp.catalogs",
    "COSECHA_ENGINE_TEST_LIFECYCLE": "cxp.catalogs",
    "COSECHA_ENGINE_TEST_PHASE": "cxp.catalogs",
    "COSECHA_ENGINE_TEST_START": "cxp.catalogs",
    "COSECHA_INSTRUMENTATION_ACTIVATE": "cxp.catalogs",
    "COSECHA_INSTRUMENTATION_CATALOG": "cxp.catalogs",
    "COSECHA_INSTRUMENTATION_COMPOSABLE_PROFILE": "cxp.catalogs",
    "COSECHA_INSTRUMENTATION_COMPOSABLE_PROFILE_NAME": "cxp.catalogs",
    "COSECHA_INSTRUMENTATION_COMPOSABLE_TIER": "cxp.catalogs",
    "COSECHA_INSTRUMENTATION_INTERFACE": "cxp.catalogs",
    "COSECHA_INSTRUMENTATION_SLOT_PROCESS_ARGV": "cxp.catalogs",
    "COSECHA_INSTRUMENTATION_SLOT_PROCESS_ENV": "cxp.catalogs",
    "COSECHA_INSTRUMENTATION_SLOT_PROCESS_SITECUSTOMIZE": "cxp.catalogs",
    "COSECHA_INSTRUMENTATION_SLOT_PY_MONITORING": "cxp.catalogs",
    "COSECHA_INSTRUMENTATION_SLOT_PY_SETPROFILE": "cxp.catalogs",
    "COSECHA_INSTRUMENTATION_SLOT_PY_SETTRACE": "cxp.catalogs",
    "COSECHA_INSTRUMENTATION_STRATEGY_IN_PROCESS": "cxp.catalogs",
    "COSECHA_INSTRUMENTATION_STRATEGY_PROCESS_WRAPPER": "cxp.catalogs",
    "COSECHA_INSTRUMENTATION_STRATEGY_SITECUSTOMIZE": "cxp.catalogs",
    "COSECHA_INSTRUMENTATION_STRUCTURED_SUMMARY": "cxp.catalogs",
    "COSECHA_PLUGIN_AFTER_SESSION_CLOSED": "cxp.catalogs",
    "COSECHA_PLUGIN_CAPABILITY_REQUIREMENTS": "cxp.catalogs",
    "COSECHA_PLUGIN_CATALOG": "cxp.catalogs",
    "COSECHA_PLUGIN_COVERAGE_SUMMARY": "cxp.catalogs",
    "COSECHA_PLUGIN_FINISH": "cxp.catalogs",
    "COSECHA_PLUGIN_INITIALIZE": "cxp.catalogs",
    "COSECHA_PLUGIN_INTERFACE": "cxp.catalogs",
    "COSECHA_PLUGIN_LIFECYCLE": "cxp.catalogs",
    "COSECHA_PLUGIN_START": "cxp.catalogs",
    "COSECHA_PLUGIN_SURFACE_PUBLICATION": "cxp.catalogs",
    "COSECHA_PLUGIN_TELEMETRY_EXPORT": "cxp.catalogs",
    "COSECHA_PLUGIN_TELEMETRY_SIDECAR_PROFILE": "cxp.catalogs",
    "COSECHA_PLUGIN_TELEMETRY_SIDECAR_PROFILE_NAME": "cxp.catalogs",
    "COSECHA_PLUGIN_TELEMETRY_SIDECAR_TIER": "cxp.catalogs",
    "COSECHA_PLUGIN_TIMING_SIDECAR_PROFILE": "cxp.catalogs",
    "COSECHA_PLUGIN_TIMING_SIDECAR_PROFILE_NAME": "cxp.catalogs",
    "COSECHA_PLUGIN_TIMING_SIDECAR_TIER": "cxp.catalogs",
    "COSECHA_PLUGIN_TIMING_SUMMARY": "cxp.catalogs",
    "COSECHA_REPORTER_ADD_TEST": "cxp.catalogs",
    "COSECHA_REPORTER_ADD_TEST_RESULT": "cxp.catalogs",
    "COSECHA_REPORTER_ARTIFACT_OUTPUT": "cxp.catalogs",
    "COSECHA_REPORTER_CATALOG": "cxp.catalogs",
    "COSECHA_REPORTER_HUMAN_OUTPUT": "cxp.catalogs",
    "COSECHA_REPORTER_INTERFACE": "cxp.catalogs",
    "COSECHA_REPORTER_PRINT_REPORT": "cxp.catalogs",
    "COSECHA_REPORTER_REPORT_LIFECYCLE": "cxp.catalogs",
    "COSECHA_REPORTER_RESULT_PROJECTION": "cxp.catalogs",
    "COSECHA_REPORTER_START": "cxp.catalogs",
    "COSECHA_REPORTER_STRUCTURED_OUTPUT": "cxp.catalogs",
    "COSECHA_RUNTIME_CATALOG": "cxp.catalogs",
    "COSECHA_RUNTIME_INTERFACE": "cxp.catalogs",
    "COSECHA_RUNTIME_LIVE_EXECUTION_OBSERVABILITY": "cxp.catalogs",
    "CURRENT_PROTOCOL_VERSION": "cxp.handshake",
    "Capability": "cxp.capabilities",
    "CapabilityAttribute": "cxp.descriptors",
    "CapabilityAttributeValue": "cxp.descriptors",
    "CapabilityCatalog": "cxp.catalogs",
    "CapabilityDescriptor": "cxp.descriptors",
    "CapabilityMatrix": "cxp.capabilities",
    "CapabilityMatrixValidationResult": "cxp.catalogs",
    "CapabilityMetadata": "cxp.capabilities",
    "CapabilityMetadataSchema": "cxp.catalogs",
    "CapabilityOperationBinding": "cxp.descriptors",
    "CapabilityProfile": "cxp.catalogs",
    "CapabilityProfileDefinitionValidationResult": "cxp.catalogs",
    "CapabilityProfileValidationResult": "cxp.catalogs",
    "CapabilityProvider": "cxp.contracts",
    "CapabilityRequirement": "cxp.catalogs",
    "CapabilitySnapshotProvider": "cxp.contracts",
    "CapabilityStability": "cxp.descriptors",
    "CapabilitySupportLevel": "cxp.descriptors",
    "CapabilityTelemetry": "cxp.catalogs",
    "CatalogCapability": "cxp.catalogs",
    "CatalogComplianceReport": "cxp.compliance",
    "CatalogOperation": "cxp.catalogs",
    "CatalogRegistry": "cxp.catalogs",
    "ComponentCapabilitySnapshot": "cxp.descriptors",
    "ComponentDependencyRule": "cxp.descriptors",
    "ComponentIdentity": "cxp.types",
    "ComponentStatus": "cxp.telemetry",
    "ConformanceTier": "cxp.catalogs",
    "ContractValidationError": "cxp.validation",
    "DEFAULT_CATALOG_REGISTRY": "cxp.catalogs",
    "DescriptorValidationResult": "cxp.catalogs",
    "EXECUTION_ENGINE_CATALOG": "cxp.catalogs",
    "EXECUTION_ENGINE_EXECUTION_STATUS": "cxp.catalogs",
    "EXECUTION_ENGINE_EXECUTION_STREAM": "cxp.catalogs",
    "EXECUTION_ENGINE_FAMILY_CATALOG": "cxp.catalogs",
    "EXECUTION_ENGINE_FAMILY_INTERFACE": "cxp.catalogs",
    "EXECUTION_ENGINE_INPUT_VALIDATION": "cxp.catalogs",
    "EXECUTION_ENGINE_INTERFACE": "cxp.catalogs",
    "EXECUTION_ENGINE_PLANNING": "cxp.catalogs",
    "EXECUTION_ENGINE_RUN": "cxp.catalogs",
    "HTTP_APPLICATION_CATALOG": "cxp.catalogs",
    "HTTP_APPLICATION_FRAMEWORK_AUTH_PROCESSING": "cxp.catalogs",
    "HTTP_APPLICATION_FRAMEWORK_CATALOG": "cxp.catalogs",
    "HTTP_APPLICATION_FRAMEWORK_CORE_TIER": "cxp.catalogs",
    "HTTP_APPLICATION_FRAMEWORK_DEPENDENCY_INJECTION": "cxp.catalogs",
    "HTTP_APPLICATION_FRAMEWORK_INTERFACE": "cxp.catalogs",
    "HTTP_APPLICATION_FRAMEWORK_ROUTING": "cxp.catalogs",
    "HTTP_APPLICATION_FRAMEWORK_SCHEMA_VALIDATION": "cxp.catalogs",
    "HTTP_APPLICATION_INTERFACE": "cxp.catalogs",
    "HTTP_TRANSPORT_AUTH_PROPAGATION": "cxp.catalogs",
    "HTTP_TRANSPORT_CATALOG": "cxp.catalogs",
    "HTTP_TRANSPORT_COOKIES": "cxp.catalogs",
    "HTTP_TRANSPORT_CORE_TIER": "cxp.catalogs",
    "HTTP_TRANSPORT_HEADERS": "cxp.catalogs",
    "HTTP_TRANSPORT_INTERFACE": "cxp.catalogs",
    "HTTP_TRANSPORT_MIDDLEWARE_OBSERVABLE": "cxp.catalogs",
    "HTTP_TRANSPORT_NETWORK_TRANSPORT": "cxp.catalogs",
    "HTTP_TRANSPORT_STREAMING": "cxp.catalogs",
    "HandshakeRequest": "cxp.handshake",
    "HandshakeResponse": "cxp.handshake",
    "Interface": "cxp.types",
    "MONGODB_AGGREGATE": "cxp.catalogs",
    "MONGODB_AGGREGATE_RICH_PROFILE": "cxp.catalogs",
    "MONGODB_AGGREGATE_RICH_PROFILE_NAME": "cxp.catalogs",
    "MONGODB_AGGREGATION": "cxp.catalogs",
    "MONGODB_BULK_WRITE": "cxp.catalogs",
    "MONGODB_CATALOG": "cxp.catalogs",
    "MONGODB_CHANGE_STREAMS": "cxp.catalogs",
    "MONGODB_COLLATION": "cxp.catalogs",
    "MONGODB_CORE_PROFILE": "cxp.catalogs",
    "MONGODB_CORE_PROFILE_NAME": "cxp.catalogs",
    "MONGODB_CORE_TIER": "cxp.catalogs",
    "MONGODB_COUNT_DOCUMENTS": "cxp.catalogs",
    "MONGODB_DELETE_MANY": "cxp.catalogs",
    "MONGODB_DELETE_ONE": "cxp.catalogs",
    "MONGODB_DISTINCT": "cxp.catalogs",
    "MONGODB_ESTIMATED_DOCUMENT_COUNT": "cxp.catalogs",
    "MONGODB_FIND": "cxp.catalogs",
    "MONGODB_FIND_ONE": "cxp.catalogs",
    "MONGODB_FULL_CAPABILITIES": "cxp.catalogs",
    "MONGODB_INSERT_MANY": "cxp.catalogs",
    "MONGODB_INSERT_ONE": "cxp.catalogs",
    "MONGODB_INTERFACE": "cxp.catalogs",
    "MONGODB_MINIMAL_CAPABILITIES": "cxp.catalogs",
    "MONGODB_PERSISTENCE": "cxp.catalogs",
    "MONGODB_PLATFORM_PROFILE": "cxp.catalogs",
    "MONGODB_PLATFORM_PROFILE_NAME": "cxp.catalogs",
    "MONGODB_PLATFORM_TIER": "cxp.catalogs",
    "MONGODB_READ": "cxp.catalogs",
    "MONGODB_REPLACE_ONE": "cxp.catalogs",
    "MONGODB_SEARCH": "cxp.catalogs",
    "MONGODB_SEARCH_PROFILE": "cxp.catalogs",
    "MONGODB_SEARCH_PROFILE_NAME": "cxp.catalogs",
    "MONGODB_SEARCH_TIER": "cxp.catalogs",
    "MONGODB_START_SESSION": "cxp.catalogs",
    "MONGODB_TEXT_SEARCH_PROFILE": "cxp.catalogs",
    "MONGODB_TEXT_SEARCH_PROFILE_NAME": "cxp.catalogs",
    "MONGODB_TOPOLOGY_DISCOVERY": "cxp.catalogs",
    "MONGODB_TRANSACTIONS": "cxp.catalogs",
    "MONGODB_UPDATE_MANY": "cxp.catalogs",
    "MONGODB_UPDATE_ONE": "cxp.catalogs",
    "MONGODB_VECTOR_SEARCH": "cxp.catalogs",
    "MONGODB_WATCH": "cxp.catalogs",
    "MONGODB_WITH_TRANSACTION": "cxp.catalogs",
    "MONGODB_WRITE": "cxp.catalogs",
    "MongoAggregationMetadata": "cxp.catalogs",
    "MongoCollationMetadata": "cxp.catalogs",
    "MongoPersistenceMetadata": "cxp.catalogs",
    "MongoSearchMetadata": "cxp.catalogs",
    "MongoTopologyDiscoveryMetadata": "cxp.catalogs",
    "MongoVectorSearchMetadata": "cxp.catalogs",
    "NegotiatedCatalogDecision": "cxp.compliance",
    "PLAN_RUN_EXECUTION_ADVANCED_PROFILE": "cxp.catalogs",
    "PLAN_RUN_EXECUTION_ADVANCED_PROFILE_NAME": "cxp.catalogs",
    "PLAN_RUN_EXECUTION_CATALOG": "cxp.catalogs",
    "PLAN_RUN_EXECUTION_CORE_PROFILE": "cxp.catalogs",
    "PLAN_RUN_EXECUTION_CORE_PROFILE_NAME": "cxp.catalogs",
    "PLAN_RUN_EXECUTION_EXECUTION_STATUS": "cxp.catalogs",
    "PLAN_RUN_EXECUTION_EXECUTION_STREAM": "cxp.catalogs",
    "PLAN_RUN_EXECUTION_INPUT_VALIDATION": "cxp.catalogs",
    "PLAN_RUN_EXECUTION_INTERFACE": "cxp.catalogs",
    "PLAN_RUN_EXECUTION_PLANNED_PROFILE": "cxp.catalogs",
    "PLAN_RUN_EXECUTION_PLANNED_PROFILE_NAME": "cxp.catalogs",
    "PLAN_RUN_EXECUTION_PLANNING": "cxp.catalogs",
    "PLAN_RUN_EXECUTION_RUN": "cxp.catalogs",
    "PLAYWRIGHT_BROWSER_CATALOG": "cxp.catalogs",
    "PLAYWRIGHT_BROWSER_CLOSE": "cxp.catalogs",
    "PLAYWRIGHT_BROWSER_CONTEXT_CLOSE": "cxp.catalogs",
    "PLAYWRIGHT_BROWSER_CONTEXT_CREATE": "cxp.catalogs",
    "PLAYWRIGHT_BROWSER_CONTEXT_MANAGEMENT": "cxp.catalogs",
    "PLAYWRIGHT_BROWSER_CORE_PROFILE": "cxp.catalogs",
    "PLAYWRIGHT_BROWSER_CORE_PROFILE_NAME": "cxp.catalogs",
    "PLAYWRIGHT_BROWSER_CORE_TIER": "cxp.catalogs",
    "PLAYWRIGHT_BROWSER_DIALOG_ACCEPT": "cxp.catalogs",
    "PLAYWRIGHT_BROWSER_DIALOG_DISMISS": "cxp.catalogs",
    "PLAYWRIGHT_BROWSER_DIALOG_HANDLING": "cxp.catalogs",
    "PLAYWRIGHT_BROWSER_DOM_INTERACTION": "cxp.catalogs",
    "PLAYWRIGHT_BROWSER_ELEMENT_CLICK": "cxp.catalogs",
    "PLAYWRIGHT_BROWSER_ELEMENT_EVALUATE": "cxp.catalogs",
    "PLAYWRIGHT_BROWSER_ELEMENT_FILL": "cxp.catalogs",
    "PLAYWRIGHT_BROWSER_ELEMENT_PRESS": "cxp.catalogs",
    "PLAYWRIGHT_BROWSER_ELEMENT_SCREENSHOT": "cxp.catalogs",
    "PLAYWRIGHT_BROWSER_ELEMENT_SELECT_OPTION": "cxp.catalogs",
    "PLAYWRIGHT_BROWSER_INTERFACE": "cxp.catalogs",
    "PLAYWRIGHT_BROWSER_LAUNCH": "cxp.catalogs",
    "PLAYWRIGHT_BROWSER_LIFECYCLE": "cxp.catalogs",
    "PLAYWRIGHT_BROWSER_LOCATOR_FILTER": "cxp.catalogs",
    "PLAYWRIGHT_BROWSER_LOCATOR_QUERY": "cxp.catalogs",
    "PLAYWRIGHT_BROWSER_LOCATOR_RESOLUTION": "cxp.catalogs",
    "PLAYWRIGHT_BROWSER_NETWORK_OBSERVATION": "cxp.catalogs",
    "PLAYWRIGHT_BROWSER_NETWORK_REQUEST_OBSERVE": "cxp.catalogs",
    "PLAYWRIGHT_BROWSER_NETWORK_RESPONSE_OBSERVE": "cxp.catalogs",
    "PLAYWRIGHT_BROWSER_OBSERVABLE_PROFILE": "cxp.catalogs",
    "PLAYWRIGHT_BROWSER_OBSERVABLE_PROFILE_NAME": "cxp.catalogs",
    "PLAYWRIGHT_BROWSER_OBSERVABLE_TIER": "cxp.catalogs",
    "PLAYWRIGHT_BROWSER_PAGE_EVALUATE": "cxp.catalogs",
    "PLAYWRIGHT_BROWSER_PAGE_GOTO": "cxp.catalogs",
    "PLAYWRIGHT_BROWSER_PAGE_GO_BACK": "cxp.catalogs",
    "PLAYWRIGHT_BROWSER_PAGE_NAVIGATION": "cxp.catalogs",
    "PLAYWRIGHT_BROWSER_PAGE_RELOAD": "cxp.catalogs",
    "PLAYWRIGHT_BROWSER_PAGE_SCREENSHOT": "cxp.catalogs",
    "PLAYWRIGHT_BROWSER_SCREENSHOT_CAPTURE": "cxp.catalogs",
    "PLAYWRIGHT_BROWSER_SCRIPT_EVALUATION": "cxp.catalogs",
    "PLAYWRIGHT_BROWSER_WAIT_CONDITIONS": "cxp.catalogs",
    "PLAYWRIGHT_BROWSER_WAIT_FOR_RESPONSE": "cxp.catalogs",
    "PLAYWRIGHT_BROWSER_WAIT_FOR_SELECTOR": "cxp.catalogs",
    "PLAYWRIGHT_BROWSER_WAIT_FOR_URL": "cxp.catalogs",
    "ProtocolVersionProvider": "cxp.contracts",
    "Provider": "cxp.types",
    "SUPPORTED_PROTOCOL_VERSIONS": "cxp.handshake",
    "TelemetryBuffer": "cxp.telemetry",
    "TelemetryBufferOverflow": "cxp.telemetry",
    "TelemetryContext": "cxp.telemetry",
    "TelemetryEvent": "cxp.telemetry",
    "TelemetryEventSpec": "cxp.catalogs",
    "TelemetryFieldRequirement": "cxp.catalogs",
    "TelemetryMetric": "cxp.telemetry",
    "TelemetryMetricSpec": "cxp.catalogs",
    "TelemetryOverflowPolicy": "cxp.telemetry",
    "TelemetryProvider": "cxp.contracts",
    "TelemetrySnapshot": "cxp.telemetry",
    "TelemetrySpan": "cxp.telemetry",
    "TelemetrySpanSpec": "cxp.catalogs",
    "TelemetryStreamProvider": "cxp.contracts",
    "TelemetryValidationResult": "cxp.catalogs",
    "UnknownCapabilityOperations": "cxp.catalogs",
    "ValidationIssue": "cxp.validation",
    "ValidationResult": "cxp.validation",
    "Version": "cxp.types",
    "WSGI_APPLICATION_CATALOG": "cxp.catalogs",
    "WSGI_APPLICATION_CORE_PROFILE": "cxp.catalogs",
    "WSGI_APPLICATION_CORE_PROFILE_NAME": "cxp.catalogs",
    "WSGI_APPLICATION_CORE_TIER": "cxp.catalogs",
    "WSGI_APPLICATION_FILE_WRAPPER": "cxp.catalogs",
    "WSGI_APPLICATION_FILE_WRAPPER_PROFILE": "cxp.catalogs",
    "WSGI_APPLICATION_FILE_WRAPPER_PROFILE_NAME": "cxp.catalogs",
    "WSGI_APPLICATION_HTTP": "cxp.catalogs",
    "WSGI_APPLICATION_INTERFACE": "cxp.catalogs",
    "WSGI_APPLICATION_OPTIMIZED_TIER": "cxp.catalogs",
    "WSGI_APPLICATION_REQUEST_BODY_READ": "cxp.catalogs",
    "WSGI_APPLICATION_REQUEST_ENVIRON_INSPECT": "cxp.catalogs",
    "WSGI_APPLICATION_RESPONSE_BODY_FILE_WRAPPER": "cxp.catalogs",
    "WSGI_APPLICATION_RESPONSE_BODY_ITERABLE": "cxp.catalogs",
    "WSGI_APPLICATION_RESPONSE_BODY_WRITE": "cxp.catalogs",
    "WSGI_APPLICATION_RESPONSE_START": "cxp.catalogs",
    "catalog_satisfies_interface": "cxp.catalogs",
    "collect_provider_capability_snapshot": "cxp.integration",
    "collect_provider_capability_snapshot_async": "cxp.integration",
    "collect_provider_telemetry": "cxp.integration",
    "collect_provider_telemetry_async": "cxp.integration",
    "evaluate_capability_matrix_against_catalog": "cxp.integration",
    "evaluate_handshake_response_against_catalog": "cxp.integration",
    "get_catalog": "cxp.catalogs",
    "is_protocol_version_supported": "cxp.handshake",
    "negotiate_capabilities": "cxp.handshake",
    "negotiate_protocol_version": "cxp.handshake",
    "negotiate_with_async_provider": "cxp.integration",
    "negotiate_with_async_provider_catalog": "cxp.integration",
    "negotiate_with_async_provider_catalog_report": "cxp.integration",
    "negotiate_with_provider": "cxp.integration",
    "negotiate_with_provider_catalog": "cxp.integration",
    "negotiate_with_provider_catalog_report": "cxp.integration",
    "register_catalog": "cxp.catalogs",
    "stream_provider_telemetry": "cxp.integration",
    "stream_provider_telemetry_async": "cxp.integration",
}

__all__ = (
    "ContractValidationError",
    "ValidationIssue",
    "ValidationResult",
    "__version__",
    "version_info",
    "Capability",
    "CapabilityCatalog",
    "CapabilityProfile",
    "CapabilityTelemetry",
    "CapabilityProfileDefinitionValidationResult",
    "CapabilityProfileValidationResult",
    "CapabilityRequirement",
    "CapabilityMatrixValidationResult",
    "CapabilityAttribute",
    "CapabilityAttributeValue",
    "CapabilityDescriptor",
    "CapabilityMetadataSchema",
    "CapabilityMetadata",
    "CapabilityMatrix",
    "CatalogComplianceReport",
    "CapabilityOperationBinding",
    "CapabilityStability",
    "CapabilitySupportLevel",
    "CatalogCapability",
    "CatalogOperation",
    "CatalogRegistry",
    "ComponentCapabilitySnapshot",
    "ComponentDependencyRule",
    "NegotiatedCatalogDecision",
    "HandshakeRequest",
    "HandshakeResponse",
    "Interface",
    "ConformanceTier",
    "CURRENT_PROTOCOL_VERSION",
    "ComponentStatus",
    "DescriptorValidationResult",
    "TelemetryEventSpec",
    "TelemetryFieldRequirement",
    "TelemetryMetricSpec",
    "TelemetrySpanSpec",
    "TelemetryValidationResult",
    "TelemetryEvent",
    "TelemetryBuffer",
    "TelemetryBufferOverflow",
    "TelemetryContext",
    "TelemetryMetric",
    "TelemetryOverflowPolicy",
    "TelemetrySpan",
    "TelemetrySnapshot",
    "AsyncCapabilityProvider",
    "AsyncCapabilitySnapshotProvider",
    "AsyncTelemetryProvider",
    "AsyncTelemetryStreamProvider",
    "CapabilityProvider",
    "CapabilitySnapshotProvider",
    "ProtocolVersionProvider",
    "TelemetryProvider",
    "TelemetryStreamProvider",
    "DEFAULT_CATALOG_REGISTRY",
    "COSECHA_ENGINE_CATALOG",
    "COSECHA_ENGINE_COLLECT",
    "COSECHA_ENGINE_DEFINITION_KNOWLEDGE",
    "COSECHA_ENGINE_DEFINITION_RESOLVE",
    "COSECHA_ENGINE_DEPENDENCIES_DESCRIBE",
    "COSECHA_ENGINE_DEPENDENCY_KNOWLEDGE",
    "COSECHA_ENGINE_DRAFT_VALIDATE",
    "COSECHA_ENGINE_DRAFT_VALIDATION",
    "COSECHA_ENGINE_INTERFACE",
    "COSECHA_ENGINE_KNOWLEDGE_QUERY_DEFINITIONS",
    "COSECHA_ENGINE_KNOWLEDGE_QUERY_REGISTRY_ITEMS",
    "COSECHA_ENGINE_KNOWLEDGE_QUERY_TESTS",
    "COSECHA_ENGINE_LIBRARY_DEFINITION_KNOWLEDGE",
    "COSECHA_ENGINE_LIFECYCLE",
    "COSECHA_ENGINE_ON_DEMAND_DEFINITION_MATERIALIZATION",
    "COSECHA_ENGINE_PLAN_ANALYZE",
    "COSECHA_ENGINE_PLAN_EXPLAIN",
    "COSECHA_ENGINE_PLAN_EXPLANATION",
    "COSECHA_ENGINE_PLAN_SIMULATE",
    "COSECHA_ENGINE_PROJECT_DEFINITION_KNOWLEDGE",
    "COSECHA_ENGINE_PROJECT_REGISTRY_KNOWLEDGE",
    "COSECHA_ENGINE_SELECTION_LABELS",
    "COSECHA_ENGINE_SESSION_FINISH",
    "COSECHA_ENGINE_SESSION_START",
    "COSECHA_ENGINE_STATIC_DEFINITION_DISCOVERY",
    "COSECHA_ENGINE_TEST_EXECUTE",
    "COSECHA_ENGINE_TEST_FINISH",
    "COSECHA_ENGINE_TEST_LIFECYCLE",
    "COSECHA_ENGINE_TEST_PHASE",
    "COSECHA_ENGINE_TEST_START",
    "COSECHA_PLUGIN_AFTER_SESSION_CLOSED",
    "COSECHA_PLUGIN_CAPABILITY_REQUIREMENTS",
    "COSECHA_PLUGIN_CATALOG",
    "COSECHA_PLUGIN_COVERAGE_SUMMARY",
    "COSECHA_PLUGIN_FINISH",
    "COSECHA_PLUGIN_INITIALIZE",
    "COSECHA_PLUGIN_INTERFACE",
    "COSECHA_PLUGIN_LIFECYCLE",
    "COSECHA_PLUGIN_START",
    "COSECHA_PLUGIN_SURFACE_PUBLICATION",
    "COSECHA_PLUGIN_TELEMETRY_SIDECAR_PROFILE",
    "COSECHA_PLUGIN_TELEMETRY_SIDECAR_PROFILE_NAME",
    "COSECHA_PLUGIN_TELEMETRY_SIDECAR_TIER",
    "COSECHA_PLUGIN_TELEMETRY_EXPORT",
    "COSECHA_PLUGIN_TIMING_SIDECAR_PROFILE",
    "COSECHA_PLUGIN_TIMING_SIDECAR_PROFILE_NAME",
    "COSECHA_PLUGIN_TIMING_SIDECAR_TIER",
    "COSECHA_PLUGIN_TIMING_SUMMARY",
    "COSECHA_INSTRUMENTATION_CATALOG",
    "COSECHA_INSTRUMENTATION_ACTIVATE",
    "COSECHA_INSTRUMENTATION_COMPOSABLE_PROFILE",
    "COSECHA_INSTRUMENTATION_COMPOSABLE_PROFILE_NAME",
    "COSECHA_INSTRUMENTATION_COMPOSABLE_TIER",
    "COSECHA_INSTRUMENTATION_INTERFACE",
    "COSECHA_INSTRUMENTATION_SLOT_PROCESS_ARGV",
    "COSECHA_INSTRUMENTATION_SLOT_PROCESS_ENV",
    "COSECHA_INSTRUMENTATION_SLOT_PROCESS_SITECUSTOMIZE",
    "COSECHA_INSTRUMENTATION_SLOT_PY_MONITORING",
    "COSECHA_INSTRUMENTATION_SLOT_PY_SETPROFILE",
    "COSECHA_INSTRUMENTATION_SLOT_PY_SETTRACE",
    "COSECHA_INSTRUMENTATION_STRATEGY_IN_PROCESS",
    "COSECHA_INSTRUMENTATION_STRATEGY_PROCESS_WRAPPER",
    "COSECHA_INSTRUMENTATION_STRATEGY_SITECUSTOMIZE",
    "COSECHA_INSTRUMENTATION_STRUCTURED_SUMMARY",
    "COSECHA_REPORTER_ADD_TEST",
    "COSECHA_REPORTER_ADD_TEST_RESULT",
    "COSECHA_REPORTER_ARTIFACT_OUTPUT",
    "COSECHA_REPORTER_CATALOG",
    "COSECHA_REPORTER_HUMAN_OUTPUT",
    "COSECHA_REPORTER_INTERFACE",
    "COSECHA_REPORTER_PRINT_REPORT",
    "COSECHA_REPORTER_REPORT_LIFECYCLE",
    "COSECHA_REPORTER_RESULT_PROJECTION",
    "COSECHA_REPORTER_START",
    "COSECHA_REPORTER_STRUCTURED_OUTPUT",
    "COSECHA_RUNTIME_CATALOG",
    "COSECHA_RUNTIME_INTERFACE",
    "COSECHA_RUNTIME_LIVE_EXECUTION_OBSERVABILITY",
    "BROWSER_AUTOMATION_CATALOG",
    "BROWSER_AUTOMATION_INTERFACE",
    "EXECUTION_ENGINE_CATALOG",
    "EXECUTION_ENGINE_EXECUTION_STATUS",
    "EXECUTION_ENGINE_EXECUTION_STREAM",
    "EXECUTION_ENGINE_FAMILY_CATALOG",
    "EXECUTION_ENGINE_FAMILY_INTERFACE",
    "EXECUTION_ENGINE_INPUT_VALIDATION",
    "EXECUTION_ENGINE_INTERFACE",
    "EXECUTION_ENGINE_PLANNING",
    "EXECUTION_ENGINE_RUN",
    "HTTP_APPLICATION_CATALOG",
    "HTTP_APPLICATION_FRAMEWORK_AUTH_PROCESSING",
    "HTTP_APPLICATION_FRAMEWORK_CATALOG",
    "HTTP_APPLICATION_FRAMEWORK_CORE_TIER",
    "HTTP_APPLICATION_FRAMEWORK_DEPENDENCY_INJECTION",
    "HTTP_APPLICATION_FRAMEWORK_INTERFACE",
    "HTTP_APPLICATION_FRAMEWORK_ROUTING",
    "HTTP_APPLICATION_FRAMEWORK_SCHEMA_VALIDATION",
    "HTTP_APPLICATION_INTERFACE",
    "WSGI_APPLICATION_CATALOG",
    "WSGI_APPLICATION_CORE_PROFILE",
    "WSGI_APPLICATION_CORE_PROFILE_NAME",
    "WSGI_APPLICATION_CORE_TIER",
    "WSGI_APPLICATION_FILE_WRAPPER",
    "WSGI_APPLICATION_FILE_WRAPPER_PROFILE",
    "WSGI_APPLICATION_FILE_WRAPPER_PROFILE_NAME",
    "WSGI_APPLICATION_HTTP",
    "WSGI_APPLICATION_INTERFACE",
    "WSGI_APPLICATION_OPTIMIZED_TIER",
    "WSGI_APPLICATION_REQUEST_BODY_READ",
    "WSGI_APPLICATION_REQUEST_ENVIRON_INSPECT",
    "WSGI_APPLICATION_RESPONSE_BODY_FILE_WRAPPER",
    "WSGI_APPLICATION_RESPONSE_BODY_ITERABLE",
    "WSGI_APPLICATION_RESPONSE_BODY_WRITE",
    "WSGI_APPLICATION_RESPONSE_START",
    "PLAYWRIGHT_BROWSER_CATALOG",
    "PLAYWRIGHT_BROWSER_CLOSE",
    "PLAYWRIGHT_BROWSER_CONTEXT_CLOSE",
    "PLAYWRIGHT_BROWSER_CONTEXT_CREATE",
    "PLAYWRIGHT_BROWSER_CONTEXT_MANAGEMENT",
    "PLAYWRIGHT_BROWSER_CORE_TIER",
    "PLAYWRIGHT_BROWSER_DIALOG_ACCEPT",
    "PLAYWRIGHT_BROWSER_DIALOG_DISMISS",
    "PLAYWRIGHT_BROWSER_DIALOG_HANDLING",
    "PLAYWRIGHT_BROWSER_DOM_INTERACTION",
    "PLAYWRIGHT_BROWSER_ELEMENT_CLICK",
    "PLAYWRIGHT_BROWSER_ELEMENT_EVALUATE",
    "PLAYWRIGHT_BROWSER_ELEMENT_FILL",
    "PLAYWRIGHT_BROWSER_ELEMENT_PRESS",
    "PLAYWRIGHT_BROWSER_ELEMENT_SCREENSHOT",
    "PLAYWRIGHT_BROWSER_ELEMENT_SELECT_OPTION",
    "PLAYWRIGHT_BROWSER_INTERFACE",
    "PLAYWRIGHT_BROWSER_LAUNCH",
    "PLAYWRIGHT_BROWSER_LIFECYCLE",
    "PLAYWRIGHT_BROWSER_LOCATOR_FILTER",
    "PLAYWRIGHT_BROWSER_LOCATOR_QUERY",
    "PLAYWRIGHT_BROWSER_LOCATOR_RESOLUTION",
    "PLAYWRIGHT_BROWSER_NETWORK_OBSERVATION",
    "PLAYWRIGHT_BROWSER_NETWORK_REQUEST_OBSERVE",
    "PLAYWRIGHT_BROWSER_NETWORK_RESPONSE_OBSERVE",
    "PLAYWRIGHT_BROWSER_OBSERVABLE_TIER",
    "PLAYWRIGHT_BROWSER_PAGE_EVALUATE",
    "PLAYWRIGHT_BROWSER_PAGE_GO_BACK",
    "PLAYWRIGHT_BROWSER_PAGE_GOTO",
    "PLAYWRIGHT_BROWSER_PAGE_NAVIGATION",
    "PLAYWRIGHT_BROWSER_PAGE_RELOAD",
    "PLAYWRIGHT_BROWSER_PAGE_SCREENSHOT",
    "PLAYWRIGHT_BROWSER_SCREENSHOT_CAPTURE",
    "PLAYWRIGHT_BROWSER_SCRIPT_EVALUATION",
    "PLAYWRIGHT_BROWSER_WAIT_CONDITIONS",
    "PLAYWRIGHT_BROWSER_WAIT_FOR_RESPONSE",
    "PLAYWRIGHT_BROWSER_WAIT_FOR_SELECTOR",
    "PLAYWRIGHT_BROWSER_WAIT_FOR_URL",
    "ASGI_APPLICATION_CATALOG",
    "ASGI_APPLICATION_EARLY_HINTS",
    "ASGI_APPLICATION_EARLY_HINTS_PROFILE",
    "ASGI_APPLICATION_EARLY_HINTS_PROFILE_NAME",
    "ASGI_APPLICATION_EXTENDED_HTTP_PROFILE",
    "ASGI_APPLICATION_EXTENDED_HTTP_PROFILE_NAME",
    "ASGI_APPLICATION_HTTP",
    "ASGI_APPLICATION_HTTP_CORE_PROFILE",
    "ASGI_APPLICATION_HTTP_CORE_PROFILE_NAME",
    "ASGI_APPLICATION_HTTP_CORE_TIER",
    "ASGI_APPLICATION_HTTP_DISCONNECT_RECEIVE",
    "ASGI_APPLICATION_HTTP_EARLY_HINT",
    "ASGI_APPLICATION_HTTP_PATH_SEND",
    "ASGI_APPLICATION_HTTP_PUSH",
    "ASGI_APPLICATION_HTTP_REQUEST_RECEIVE",
    "ASGI_APPLICATION_HTTP_RESPONSE_BODY",
    "ASGI_APPLICATION_HTTP_RESPONSE_START",
    "ASGI_APPLICATION_HTTP_SCOPE_INSPECT",
    "ASGI_APPLICATION_HTTP_SERVER_PUSH",
    "ASGI_APPLICATION_HTTP_TRAILERS",
    "ASGI_APPLICATION_HTTP_ZERO_COPY_SEND",
    "ASGI_APPLICATION_INTERFACE",
    "ASGI_APPLICATION_LIFESPAN",
    "ASGI_APPLICATION_LIFESPAN_PROFILE",
    "ASGI_APPLICATION_LIFESPAN_PROFILE_NAME",
    "ASGI_APPLICATION_LIFESPAN_SHUTDOWN_COMPLETE",
    "ASGI_APPLICATION_LIFESPAN_SHUTDOWN_FAILED",
    "ASGI_APPLICATION_LIFESPAN_SHUTDOWN_RECEIVE",
    "ASGI_APPLICATION_LIFESPAN_SCOPE_INSPECT",
    "ASGI_APPLICATION_LIFESPAN_STARTUP_COMPLETE",
    "ASGI_APPLICATION_LIFESPAN_STARTUP_FAILED",
    "ASGI_APPLICATION_LIFESPAN_STARTUP_RECEIVE",
    "ASGI_APPLICATION_PATH_SEND",
    "ASGI_APPLICATION_REALTIME_PROFILE",
    "ASGI_APPLICATION_REALTIME_PROFILE_NAME",
    "ASGI_APPLICATION_REALTIME_TIER",
    "ASGI_APPLICATION_TLS",
    "ASGI_APPLICATION_TLS_AWARE_PROFILE",
    "ASGI_APPLICATION_TLS_AWARE_PROFILE_NAME",
    "ASGI_APPLICATION_TLS_SCOPE_INSPECT",
    "ASGI_APPLICATION_TRAILERS",
    "ASGI_APPLICATION_WEBSOCKET",
    "ASGI_APPLICATION_WEBSOCKET_ACCEPT",
    "ASGI_APPLICATION_WEBSOCKET_CLOSE",
    "ASGI_APPLICATION_WEBSOCKET_CONNECT_RECEIVE",
    "ASGI_APPLICATION_WEBSOCKET_DENIAL_PROFILE",
    "ASGI_APPLICATION_WEBSOCKET_DENIAL_PROFILE_NAME",
    "ASGI_APPLICATION_WEBSOCKET_DENIAL_RESPONSE",
    "ASGI_APPLICATION_WEBSOCKET_DISCONNECT_RECEIVE",
    "ASGI_APPLICATION_WEBSOCKET_HTTP_RESPONSE_BODY",
    "ASGI_APPLICATION_WEBSOCKET_HTTP_RESPONSE_START",
    "ASGI_APPLICATION_WEBSOCKET_RECEIVE",
    "ASGI_APPLICATION_WEBSOCKET_SCOPE_INSPECT",
    "ASGI_APPLICATION_WEBSOCKET_SEND",
    "ASGI_APPLICATION_WEB_CORE_PROFILE",
    "ASGI_APPLICATION_WEB_CORE_PROFILE_NAME",
    "ASGI_APPLICATION_WEB_CORE_TIER",
    "ASGI_APPLICATION_ZERO_COPY_SEND",
    "HTTP_TRANSPORT_AUTH_PROPAGATION",
    "HTTP_TRANSPORT_CATALOG",
    "HTTP_TRANSPORT_COOKIES",
    "HTTP_TRANSPORT_CORE_TIER",
    "HTTP_TRANSPORT_HEADERS",
    "HTTP_TRANSPORT_INTERFACE",
    "HTTP_TRANSPORT_MIDDLEWARE_OBSERVABLE",
    "HTTP_TRANSPORT_NETWORK_TRANSPORT",
    "HTTP_TRANSPORT_STREAMING",
    "MongoAggregationMetadata",
    "MongoCollationMetadata",
    "MongoPersistenceMetadata",
    "MongoSearchMetadata",
    "MongoTopologyDiscoveryMetadata",
    "MongoVectorSearchMetadata",
    "MONGODB_CATALOG",
    "MONGODB_CORE_PROFILE",
    "MONGODB_CORE_PROFILE_NAME",
    "MONGODB_CORE_TIER",
    "MONGODB_COLLATION",
    "MONGODB_AGGREGATE",
    "MONGODB_AGGREGATE_RICH_PROFILE",
    "MONGODB_AGGREGATE_RICH_PROFILE_NAME",
    "MONGODB_AGGREGATION",
    "MONGODB_BULK_WRITE",
    "MONGODB_CHANGE_STREAMS",
    "MONGODB_COUNT_DOCUMENTS",
    "MONGODB_DELETE_MANY",
    "MONGODB_DELETE_ONE",
    "MONGODB_DISTINCT",
    "MONGODB_ESTIMATED_DOCUMENT_COUNT",
    "MONGODB_FIND",
    "MONGODB_FIND_ONE",
    "MONGODB_FULL_CAPABILITIES",
    "MONGODB_INSERT_MANY",
    "MONGODB_INSERT_ONE",
    "MONGODB_INTERFACE",
    "MONGODB_MINIMAL_CAPABILITIES",
    "MONGODB_PERSISTENCE",
    "MONGODB_PLATFORM_PROFILE",
    "MONGODB_PLATFORM_PROFILE_NAME",
    "MONGODB_PLATFORM_TIER",
    "MONGODB_READ",
    "MONGODB_REPLACE_ONE",
    "MONGODB_SEARCH",
    "MONGODB_TEXT_SEARCH_PROFILE",
    "MONGODB_TEXT_SEARCH_PROFILE_NAME",
    "MONGODB_SEARCH_PROFILE",
    "MONGODB_SEARCH_PROFILE_NAME",
    "MONGODB_SEARCH_TIER",
    "MONGODB_START_SESSION",
    "MONGODB_TOPOLOGY_DISCOVERY",
    "MONGODB_TRANSACTIONS",
    "MONGODB_UPDATE_MANY",
    "MONGODB_UPDATE_ONE",
    "MONGODB_VECTOR_SEARCH",
    "MONGODB_WATCH",
    "MONGODB_WITH_TRANSACTION",
    "MONGODB_WRITE",
    "PLAN_RUN_EXECUTION_CATALOG",
    "PLAN_RUN_EXECUTION_ADVANCED_PROFILE",
    "PLAN_RUN_EXECUTION_ADVANCED_PROFILE_NAME",
    "PLAN_RUN_EXECUTION_CORE_PROFILE",
    "PLAN_RUN_EXECUTION_CORE_PROFILE_NAME",
    "PLAN_RUN_EXECUTION_EXECUTION_STATUS",
    "PLAN_RUN_EXECUTION_EXECUTION_STREAM",
    "PLAN_RUN_EXECUTION_INPUT_VALIDATION",
    "PLAN_RUN_EXECUTION_INTERFACE",
    "PLAN_RUN_EXECUTION_PLANNED_PROFILE",
    "PLAN_RUN_EXECUTION_PLANNED_PROFILE_NAME",
    "PLAN_RUN_EXECUTION_PLANNING",
    "PLAN_RUN_EXECUTION_RUN",
    "PLAYWRIGHT_BROWSER_CORE_PROFILE",
    "PLAYWRIGHT_BROWSER_CORE_PROFILE_NAME",
    "PLAYWRIGHT_BROWSER_OBSERVABLE_PROFILE",
    "PLAYWRIGHT_BROWSER_OBSERVABLE_PROFILE_NAME",
    "Provider",
    "SUPPORTED_PROTOCOL_VERSIONS",
    "UnknownCapabilityOperations",
    "catalog_satisfies_interface",
    "Version",
    "ComponentIdentity",
    "collect_provider_capability_snapshot",
    "collect_provider_capability_snapshot_async",
    "collect_provider_telemetry",
    "collect_provider_telemetry_async",
    "evaluate_capability_matrix_against_catalog",
    "evaluate_handshake_response_against_catalog",
    "negotiate_with_async_provider_catalog_report",
    "negotiate_with_async_provider_catalog",
    "get_catalog",
    "is_protocol_version_supported",
    "negotiate_capabilities",
    "negotiate_protocol_version",
    "negotiate_with_async_provider",
    "negotiate_with_provider_catalog_report",
    "negotiate_with_provider_catalog",
    "negotiate_with_provider",
    "register_catalog",
    "stream_provider_telemetry",
    "stream_provider_telemetry_async",
)


def __getattr__(name: str):
    module_name = _EXPORT_MODULES.get(name)
    if module_name is None:
        raise AttributeError(name)
    if module_name != "cxp.validation":
        warn(
            f"cxp.{name} belongs to the legacy component protocol; "
            "use cxp.exchange and owner-authored catalogs instead",
            DeprecationWarning,
            stacklevel=2,
        )
    value = getattr(import_module(module_name), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted({*globals(), *__all__})
