from cxp.catalogs.interfaces.execution.family import (
    EXECUTION_ENGINE_FAMILY_CATALOG,
    EXECUTION_ENGINE_FAMILY_INTERFACE,
)
from cxp.catalogs.interfaces.execution.plan_run import (
    PLAN_RUN_EXECUTION_CATALOG,
    PLAN_RUN_EXECUTION_EXECUTION_STATUS,
    PLAN_RUN_EXECUTION_EXECUTION_STREAM,
    PLAN_RUN_EXECUTION_INPUT_VALIDATION,
    PLAN_RUN_EXECUTION_INTERFACE,
    PLAN_RUN_EXECUTION_PLANNING,
    PLAN_RUN_EXECUTION_RUN,
    PLAN_RUN_OP_CANCEL,
    PLAN_RUN_OP_STATUS,
)

# Compatibility aliases for the pre-family execution catalog API.
EXECUTION_ENGINE_CATALOG = PLAN_RUN_EXECUTION_CATALOG
EXECUTION_ENGINE_INTERFACE = PLAN_RUN_EXECUTION_INTERFACE
EXECUTION_ENGINE_RUN = PLAN_RUN_EXECUTION_RUN
EXECUTION_ENGINE_PLANNING = PLAN_RUN_EXECUTION_PLANNING
EXECUTION_ENGINE_INPUT_VALIDATION = PLAN_RUN_EXECUTION_INPUT_VALIDATION
EXECUTION_ENGINE_EXECUTION_STATUS = PLAN_RUN_EXECUTION_EXECUTION_STATUS
EXECUTION_ENGINE_EXECUTION_STREAM = PLAN_RUN_EXECUTION_EXECUTION_STREAM

__all__ = (
    "EXECUTION_ENGINE_CATALOG",
    "EXECUTION_ENGINE_EXECUTION_STATUS",
    "EXECUTION_ENGINE_EXECUTION_STREAM",
    "EXECUTION_ENGINE_FAMILY_CATALOG",
    "EXECUTION_ENGINE_FAMILY_INTERFACE",
    "EXECUTION_ENGINE_INPUT_VALIDATION",
    "EXECUTION_ENGINE_INTERFACE",
    "EXECUTION_ENGINE_PLANNING",
    "EXECUTION_ENGINE_RUN",
    "PLAN_RUN_OP_CANCEL",
    "PLAN_RUN_OP_STATUS",
)
